version: "3"

services:
  app:
    container_name: recipe_app
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "./manage.py wait_for_db &&
        ./manage.py migrate &&
        ./manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=mysuperpassword
      - MEDIA_ROOT=/vol/web/media
      - STATIC_ROOT=/vol/web/static
    depends_on:
      - db

  db:
    container_name: recipe_db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysuperpassword
